# Generated by Django 3.2.12 on 2022-07-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='usd',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
    ]
