# Generated by Django 3.2.12 on 2022-07-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_wallet_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invested',
            field=models.BooleanField(default=False),
        ),
    ]
